name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      # output some meta info (i.e: context) that automatically passed into these jobs & steps.
      #   try to output some general info about this workflow & the event trigger.
      - name: Output GitHub context
        #   "github" = a special identifier/reserver word coming from github
        run: echo "{{ toJSON(github) }}"
